#!/bin/bash
echo "🌅 Starting Day/Night Cycle Test..."
echo ""
echo "Server startet bei 12:00 Mittag"
echo "Ein voller Tag-Nacht-Zyklus dauert 15 Minuten"
echo ""
echo "Zeitplan:"
echo "  12:00 - Start (Mittag, Sonne oben)"
echo "  15:00 - Nachmittag"
echo "  18:00 - Sonnenuntergang beginnt"
echo "  21:00 - Nacht"
echo "  00:00 - Mitternacht"
echo "  03:00 - Tiefe Nacht"
echo "  06:00 - Sonnenaufgang beginnt"
echo "  09:00 - Morgen"
echo "  12:00 - Wieder Mittag"
echo ""
echo "Drücke F3 im Client um Debug-Info zu sehen"
echo "Schaue in die Logs mit: RUST_LOG=info"
echo ""
